routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

 Route::get('/', [
     'as' => 'home',
     'uses' => 'HomeController@index'
 ]);

 /*
Route::get('/', function() {
    return View('auth.login');
})->name('loginn');
*/

Route::get('/reset_password', [
    'as' => 'auth.reset_password',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

Route::get('/announcements', [
    'as' => 'home.announcements',
    'uses' => 'HomeController@announcements'
]);

Route::get('/publishes', [
    'as' => 'home.publishes',
    'uses' => 'HomeController@publishes'
]);

Route::get('/publishes/{publish}/download', [
    'as' => 'home.download',
    'uses' => 'HomeController@publishDownload'
]);

Route::get('/announcements/{announcement}', [
    'as' => 'home.announcements.show',
    'uses' => 'HomeController@getAnnouncement'
]);

Route::get('announcements/{announcement}/show', 'AnnouncementController@show')->name('announcements.show');

//-----------POSTULANT CREATE--------------//
Route::get('announcements/{announcement}/postulans/create', [
    'as' => 'postulans.create',
    'uses' => 'PostulantController@create',
]);
Route::post('announcementss/{announcement}/postulans/store', [
    'as' => 'postulans.stores',
    'uses' => 'PostulantController@store',
]);
Route::get('{announcement}/postulans/{postulant}/show', [
    'as' => 'postulants.show',
    'uses' => 'PostulantController@show',
]);
Route::get('announcements/{announcement}/postulans/{postulant}/edit', [
    'as' => 'postulans.edit',
    'uses' => 'PostulantController@edit',
]);
Route::post('announcementss/{announcement}/postulans/{postulant}/edit', [
    'as' => 'postulans.updates',
    'uses' => 'PostulantController@update',
]);
Route::get('postulans/{postulant}/print', [
    'as' => 'postulans.print',
    'uses' => 'PostulantController@print',
]);

Route::get('avisos', [
    'as' => 'avisos',
    'uses' => 'AvisosController@index',
]);

Route::get('avisos/{aviso}', [
    'as' => 'avisos.download',
    'uses' => 'AvisosController@download',
]);

////////////////////// ADMIN ROUTES ///////////////////
Route::group(['prefix' => 'admin', 'middleware' => ['auth'], 'as' => 'admin.', 'namespace' => 'Admin'], function() {
    Route::get('dashboard', [
        'as' => 'dashboard',
        'uses' => 'HomeController@index'
    ]);

    //------------ USERS --------------//
    Route::get('users', [
        'as' => 'users.index',
        'uses' => 'UserController@index',
    ])->middleware('permission:list users');
    Route::get('users/create', [
        'as' => 'users.create',
        'uses' => 'UserController@create',
    ])->middleware('permission:create users');
    Route::post('users/store', [
        'as' => 'users.store',
        'uses' => 'UserController@store',
    ])->middleware('permission:create users');
    Route::get('users/{user}/edit', [
        'as' => 'users.edit',
        'uses' => 'UserController@edit',
    ])->middleware('permission:edit users');
    Route::put('users/{user}', [
        'as' => 'users.update',
        'uses' => 'UserController@update',
    ])->middleware('permission:edit users');
    Route::patch('users/{user}', [
        'as' => 'users.update',
        'uses' => 'UserController@update',
    ])->middleware('permission:edit users');
    Route::delete('users/{user}', [
        'as' => 'users.destroy',
        'uses' => 'UserController@destroy',
    ])->middleware('permission:delete users');

    //------------ ROLES --------------//
    Route::get('roles', [
        'as' => 'roles.index',
        'uses' => 'RoleController@index',
    ])->middleware('permission:list roles');
    Route::get('roles/create', [
        'as' => 'roles.create',
        'uses' => 'RoleController@create',
    ])->middleware('permission:list roles');
    Route::post('roles/store', [
        'as' => 'roles.store',
        'uses' => 'RoleController@store',
    ])->middleware('permission:list roles');
    Route::get('roles/{role}/edit', [
        'as' => 'roles.edit',
        'uses' => 'RoleController@edit',
    ])->middleware('permission:list roles');
    Route::put('roles/{role}', [
        'as' => 'roles.update',
        'uses' => 'RoleController@update',
    ])->middleware('permission:list roles');
    Route::patch('roles/{role}', [
        'as' => 'roles.update',
        'uses' => 'RoleController@update',
    ])->middleware('permission:list roles');
    Route::delete('roles/{role}', [
        'as' => 'roles.destroy',
        'uses' => 'RoleController@destroy',
    ])->middleware('permission:list roles');

    //------------ announcements --------------//
    Route::get('announcements', [
        'as' => 'announcements.index',
        'uses' => 'AnnouncementController@index',
    ])->middleware('permission:list announcements');
    Route::get('announcements/{announcement}/show', [
        'as' => 'announcements.show',
        'uses' => 'AnnouncementController@show',
    ])->middleware('permission:show announcements');
    Route::get('announcements/create', [
        'as' => 'announcements.create',
        'uses' => 'AnnouncementController@create',
    ])->middleware('permission:create announcements');
    Route::post('announcements/store', [
        'as' => 'announcements.store',
        'uses' => 'AnnouncementController@store',
    ])->middleware('permission:create announcements');
    Route::get('announcements/{announcement}/show', [
        'as' => 'announcements.show',
        'uses' => 'AnnouncementController@show',
    ])->middleware('permission:show announcements');
    Route::get('announcements/{announcement}/edit', [
        'as' => 'announcements.edit',
        'uses' => 'AnnouncementController@edit',
    ])->middleware('permission:edit announcements');
    Route::put('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::patch('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::delete('announcements/{announcement}', [
        'as' => 'announcements.destroy',
        'uses' => 'AnnouncementController@destroy',
    ])->middleware('permission:delete announcements');

    Route::get('announcements/{announcement}/files', [
        'as' => 'requirements.files',
        'uses' => 'AnnouncementController@requirement',
    ]);

    Route::get('announcements/{announcement}/publish', [
        'as' => 'announcements.publish',
        'uses' => 'AnnouncementController@publish',
    ])->middleware('permission:list publishes');

    Route::post('announcements/{announcement}/store', [
        'as' => 'resannoun.store',
        'uses' => 'AnnouncementController@publishStore',
    ])->middleware('permission:create publishes');
        

    //------------ Postulants --------------//
    Route::get('{announcement}/postulants', [
        'as' => 'postulants.index',
        'uses' => 'PostulantController@index',
    ])->middleware('permission:list postulants');
    Route::get('announcements/{announcement}/postulants/{postulant}/files', [
        'as' => 'postulants.show',
        'uses' => 'PostulantController@show',
    ]);
    Route::get('{announcement}/postulants/create', [
        'as' => 'postulants.create',
        'uses' => 'PostulantController@create',
    ])->middleware('permission:create postulants');
    Route::get('{announcement}/postulants/{postulant}/requirement/{requirement}/checked', [
        'as' => 'postulants.checkedFile',
        'uses' => 'PostulantController@checked',
    ]);
    Route::post('{announcement}/postulants/store', [
        'as' => 'postulants.store',
        'uses' => 'PostulantController@store',
    ])->middleware('permission:create postulants');
    Route::get('{announcement}/postulants/{postulant}/edit', [
        'as' => 'postulants.edit',
        'uses' => 'PostulantController@edit',
    ])->middleware('permission:edit postulants');
    Route::put('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.update',
        'uses' => 'PostulantController@update',
    ])->middleware('permission:edit postulants');
    Route::patch('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.update',
        'uses' => 'PostulantController@update',
    ])->middleware('permission:edit postulants');
    Route::delete('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.destroy',
        'uses' => 'PostulantController@destroy',
    ])->middleware('permission:delete postulants');
    
    Route::get('{announcement}/postulants/{postulant}/calificate', [
        'as' => 'postulants.calificate',
        'uses' => 'PostulantController@calificate'
    ]);

    //-------------- AREAS ------------------//
    Route::get('academics/{academic}/areas', [
        'as' => 'areas.index',
        'uses' => 'AreaController@index',
    ]);
    Route::get('academics/{academic}/areas/create', [
        'as' => 'areas.create',
        'uses' => 'AreaController@create',
    ]);
    Route::post('academics/{academic}/areas/store', [
        'as' => 'areas.store',
        'uses' => 'AreaController@store',
    ]);
    Route::get('academics/{academic}/areas/{area}/edit', [
        'as' => 'areas.edit',
        'uses' => 'AreaController@edit',
    ]);
    Route::put('academics/{academic}/areas/{area}', [
        'as' => 'areas.update',
        'uses' => 'AreaController@update',
    ]);
    Route::patch('academics/{academic}/areas/{area}', [
        'as' => 'areas.update',

resources/views/announcement.blade.php
@extends('layouts.app')

@section('content')
    <div class="animated fadeIn">

            <div class="card-header text-center title-panel bg-dark text-white mb-3" style="font-family: cursive !important; font-size: 2em; background: rgba(0,0,0,0.8) !important">CONVOCATORIAS</div>
            <div class="card-columns">
    
                @foreach($announcements as $announcement)
                    @include('layouts.announcement', [ 'item' => $announcement ])
                @endforeach
    
            </div>

    </div>
@endsection

@section('scripts')
    <script>
        let title = $("#announcement_id")
        let content = $("#announcement_content")
        let list_requirements = $("#list_requirements_required")
        let list_extra = $("#list_requirements")
        let anouncement_modal = $("#announcement")
        let anouncement_id = $("#id_announcement")

        const show_announcement = (announcement, requeriments) => {
            clear()
            requeriments.forEach(item => {
                if (item.required == true)
                    list_requirements.append('<li><b>' + item.description + '</b></li>')
                else
                    list_extra.append('<li><b>' + item.description + '</b></li>')
            })

            title.html("<b class='text-center'>" + announcement.title + "</b>")
            content.html("<b class='text-center'>" + announcement.description + "</b>")
            list_requirements.html()

            anouncement_id.val(announcement.id)

            anouncement_modal.modal()
        };

        const clear = () => {
            title.html('')
            content.html('')
            list_requirements.html('')
            list_extra.html('')
        }

        const insertCode = (e) => {
            anouncement_modal.modal('hide')

            Swal.fire({
                title: 'Postulate',
                html: `<h2 style='font-family: cursive'><strong>Ingrese codigo de postulacion</strong></2>.`,
                input: 'text',
                inputAttributes: {
                    autocapitalize: 'off'
                },
                showCancelButton: true,
                confirmButtonText: 'Entrar',
                showLoaderOnConfirm: true,
                preConfirm: (text) => {
                    // TODO cambiar la ur cuando se pone en produccion
                    return fetch(`http://localhost:8000/admin/announcements/${anouncement_id.val()}/compare`, {
                        method: 'POST',
                        body: new URLSearchParams({code: text}),
                        headers: new Headers({
                            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }),
                    }).then(response => {
                        console.log('response')
                        if (!response.ok) {
                            throw new Error(response.statusText)
                        }
                        return response.json()
                    })
                },
                allowOutsideClick: () => !Swal.isLoading()
            }).then(({ value }) => {
                const { error, code } = value

                if ( code == 400) {
                    toastr.error(error)
                }

                if ( code == 200 ) {
                    location.replace('{{ route('admin.announcements.index') }}')
                    toastr.success('codigo correcto')
                }
            })

        }
    </script>
@endsection

resources/views/avisos.blade.php
@extends('layouts.app')

@section('content')
hola
@endsection

resources/views/postulant_register.blade.php
@extends('auth.layouts.auth')

@section('htmlheader_title')
    Register
@endsection

@section('styles')
  <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('css/template.css') }}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <span class="login100-form-title">
                REGISTRARSE - {{$announcement->title}}
            </span>

            <form class="form-horizontal" action="{{ route('postulans.stores', [ 'announcement' => $announcement ]) }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('name')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('name')? $errors->first('name') : 'Nombre completo es requerido' }}">
                            <input class="input100" type="text" name="name" placeholder="Nombres"  value="{{ old('name')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-user" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('lastname')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('lastname')? $errors->first('lastname') : 'Apellidos es requerido' }}">
                            <input class="input100" type="text" name="lastname" placeholder="Apellidos"  value="{{ old('lastname')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-user" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('ci')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('ci')? $errors->first('ci') : 'C.I. es requerido' }}">
                            <input class="input100" type="text" name="ci" placeholder="Carnet Identidad"  value="{{ old('ci')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-list" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('cod_sis')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('cod_sis')? $errors->first('cod_sis') : 'Cod. SIS es requerido' }}">
                            <input class="input100" type="text" name="cod_sis" placeholder="Codigo SIS"  value="{{ old('cod_sis')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('gender')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('gender')? $errors->first('gender') : 'Este es requerido' }}">
                            <select class="input100 {{ $errors->has('gender') ? 'is-invalid' : '' }}" name="gender" type="text">
                                <option disabled hidden selected>Seleccione sexo</option>
                                <option value="M" {{ ( old('gender', isset($user) && $user->gender == 'M') ? 'selected' : '') }}>MASCULINO</option>
                                <option value="F" {{ ( old('gender', isset($user) && $user->gender == 'F') ? 'selected' : '') }}>FEMENINO</option>
                            </select>

                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-users" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('address')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('address')? $errors->first('address') : 'Direccion es requerido' }}">
                            <input class="input100" type="text" name="address" placeholder="Direccion"  value="{{ old('address')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-thumb-tack" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('email')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('email')? $errors->first('email') : 'E-mail valido es requerido: example@abc.xyz' }}">
                            <input class="input100" type="text" name="email" placeholder="Email" value="{{ old('email') }}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('phone')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('phone')? $errors->first('phone') : 'Telefono es requerido' }}">
                            <input class="input100" type="text" name="phone" placeholder="Telefono/Celular"  value="{{ old('phone')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('nro_docs')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('nro_docs')? $errors->first('nro_docs') : 'Nro de documentos es requerido' }}">
                            <input class="input100" type="text" name="nro_docs" placeholder="Nro de documentos"  value="{{ old('nro_docs')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-archive" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-6 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('nro_certificates')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('nro_certificates')? $errors->first('nro_certificates') : 'Nro de certificados es requerido' }}">
                            <input class="input100" type="text" name="nro_certificates" placeholder="Nro de certificados"  value="{{ old('nro_certificates')}}">
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-archive" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="col-md-12 mb-3">
                        <div class="wrap-input100 validate-input {{ $errors->has('item_id')? 'alert-validate' : '' }}" data-validate="{{ $errors->has('item_id')? $errors->first('item_id') : 'Este es requerido' }}">
                            <select class="input100 {{ $errors->has('item_id') ? 'is-invalid' : '' }}" name="item_id" type="text">
                                <option disabled hidden selected>Seleccione item</option>
                                @foreach($items as $item)
                                    <option value="{{ $item->id }}" {{ (isset($announcement) && $item->id == $announcement->item_id) ? 'selected' : '' }}>{{ $item->name }}</option>
                                @endforeach
                            </select>

                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-users" aria-hidden="true"></i>
                            </span>
                        </div>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Register
                        </button>
                    </div>

                    <div class="text-center p-t-136">
                        <a class="txt2" href="{{ url('/login') }}">
                            I already have a membership
                            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

    @include('auth.scripts')
</body>

@endsection

resources/views/publishes.blade.php
@extends('layouts.app')

@section('content')
    <div class="animated fadeIn">

            <div class="card-header text-center title-panel bg-dark text-white mb-3" style="font-family: cursive !important; font-size: 2em; background: rgba(0,0,0,0.8) !important">
                Notas de convocatorias publicadas
            </div>
            <div class="card-columns">
    
                @foreach($publishes as $publish)
                    @include('layouts.publish', [ 'item' => $publish ])
                @endforeach
    
            </div>

    </div>
@endsection

@section('scripts')
    <script>
        let title = $("#announcement_id")
        let content = $("#announcement_content")
        let list_requirements = $("#list_requirements_required")
        let list_extra = $("#list_requirements")
        let anouncement_modal = $("#announcement")
        let anouncement_id = $("#id_announcement")

        const show_announcement = (announcement, requeriments) => {
            clear()
            requeriments.forEach(item => {
                if (item.required == true)
                    list_requirements.append('<li><b>' + item.description + '</b></li>')
                else
                    list_extra.append('<li><b>' + item.description + '</b></li>')
            })

            title.html("<b class='text-center'>" + announcement.title + "</b>")
            content.html("<b class='text-center'>" + announcement.description + "</b>")
            list_requirements.html()

            anouncement_id.val(announcement.id)

            anouncement_modal.modal()
        };

        const clear = () => {
            title.html('')
            content.html('')
            list_requirements.html('')
            list_extra.html('')
        }

        const insertCode = (e) => {
            anouncement_modal.modal('hide')

            Swal.fire({
                title: 'Postulate',
                html: `<h2 style='font-family: cursive'><strong>Ingrese codigo de postulacion</strong></2>.`,
                input: 'text',
                inputAttributes: {
                    autocapitalize: 'off'
                },
                showCancelButton: true,
                confirmButtonText: 'Entrar',
                showLoaderOnConfirm: true,
                preConfirm: (text) => {
                    // TODO cambiar la ur cuando se pone en produccion
                    return fetch(`http://localhost:8000/admin/announcements/${anouncement_id.val()}/compare`, {
                        method: 'POST',
                        body: new URLSearchParams({code: text}),
                        headers: new Headers({
                            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }),
                    }).then(response => {
                        console.log('response')
                        if (!response.ok) {
                            throw new Error(response.statusText)
                        }
                        return response.json()
                    })
                },
                allowOutsideClick: () => !Swal.isLoading()
            }).then(({ value }) => {
                const { error, code } = value

                if ( code == 400) {
                    toastr.error(error)
                }

                if ( code == 200 ) {
                    location.replace('{{ route('admin.announcements.index') }}')
                    toastr.success('codigo correcto')
                }
            })

        }
    </script>
@endsection